"use strict;";

const STORAGE_KEY = "BREWFAE_SAVE";

const adjectives = [
    "Absent-minded",
    "Adolescent",
    "Aged",
    "Ambitious",
    "Angry",
    "Athletic",
    "Attractive",
    "Awkward",
    "Beautiful",
    "Bitter",
    "Blunt",
    "Boastful",
    "Calculating",
    "Calm",
    "Captivating",
    "Cautious",
    "Charming",
    "City-dwelling",
    "Clumsy",
    "Colourful",
    "Cowardly",
    "Craven",
    "Creative",
    "Curious",
    "Deceptive",
    "Defiant",
    "Determined",
    "Diplomatic",
    "Disturbing",
    "Doomed",
    "Down to earth",
    "Driven",
    "Eager",
    "Earthy",
    "Easily frightened",
    "Educated",
    "Eerie",
    "Efficient",
    "Elderly",
    "Eldritch",
    "Elegant",
    "Embittered",
    "Emotional",
    "Empathic",
    "Erudite",
    "Exiled",
    "Exotic",
    "Experienced",
    "Fast",
    "Fated",
    "Flamboyant",
    "Foolish",
    "Forgetful",
    "Garish",
    "Ghoulish",
    "Good-natured",
    "Graceful",
    "Greedy",
    "Gregarious",
    "Grim",
    "Grounded",
    "Grubby",
    "Guarded",
    "Handsome",
    "Hardy",
    "Hideous",
    "Hilarious",
    "Honest",
    "Honourable",
    "Humble",
    "Impulsive",
    "Independent",
    "Inquisitive",
    "Intuitive",
    "Jaded",
    "Jovial",
    "Joyful",
    "Keen-Eared",
    "Keen-Sensed",
    "Kindly",
    "Lawful",
    "Lazy",
    "Learned",
    "Loud",
    "Lucky",
    "Mad",
    "Mishapen",
    "Morose",
    "Mysterious",
    "Mystical",
    "Naive",
    "Noble",
    "Nosey",
    "Oafish",
    "Observant",
    "Old",
    "Optimistic",
    "Orderly",
    "Otherworldly",
    "Outcast",
    "Outrageous",
    "Pacifist",
    "Peaceful",
    "Perceptive",
    "Pessimistic",
    "Petulant",
    "Pious",
    "Plucky",
    "Pompous",
    "Ponderous",
    "Possessed",
    "Prim",
    "Quick",
    "Quiet",
    "Refined",
    "Regal",
    "Resilient",
    "Resourceful",
    "Rude",
    "Rugged",
    "Sarcastic",
    "Savvy",
    "Scarred",
    "Scatterbrained",
    "Scrawny",
    "Seasoned",
    "Seeking",
    "Self-sufficient",
    "Serene",
    "Serious",
    "Sharp-eyed",
    "Sickly",
    "Sincere",
    "Sinister",
    "Skeptical",
    "Slothful",
    "Sly",
    "Spiritual",
    "Stalwart",
    "Steadfast",
    "Stealthy",
    "Strait-laced",
    "Strong-Willed",
    "Strong",
    "Stubborn",
    "Studious",
    "Suave",
    "Superior",
    "Suspicious",
    "Swarthy",
    "Swift",
    "Tactful",
    "Teenaged",
    "Thoughtful",
    "Timid",
    "Tough",
    "Uncanny",
    "Uncouth",
    "Unhinged",
    "Unlucky",
    "Unpredictable",
    "Untamed",
    "Unusual",
    "Vain",
    "Vengeful",
    "Veteran",
    "Virtuous",
    "Warlike",
    "Warped",
    "Wealthy",
    "Weathered",
    "Weird",
    "Well mannered",
    "Well read",
    "Whimsical",
    "Wild",
    "Wise",
    "Young",
];

const approaches = [
    "Careful",
    "Clever",
    "Flashy",
    "Forceful",
    "Quick",
    "Sneaky",
];

const aspects = [
    { text: "Always carry...", value: "Always carry" },
    { text: "Bearer of...", value: "Bearer of" },
    { text: "I always say...", value: "I always say" },
    { text: "I believe...", value: "I believe" },
    { text: "I know...", value: "I know" },
    { text: "I love...", value: "I love" },
    { text: "I've met...", value: "I've met" },
    { text: "Member of...", value: "Member of" },
    { text: "They call me...", value: "They call me" },
    { text: "Wielder of...", value: "Wielder of" },
];

const classes = [
    "Alchemist",
    "Archaeologist",
    "Archivist",
    "Artisan",
    "Artist",
    "Attendant",
    "Barbarian",
    "Bard",
    "Beast Handler",
    "Bureaucrat",
    "Cartographer",
    "Cleric",
    "Con Artist",
    "Crafter",
    "Demon Hunter",
    "Duelist",
    "Explorer",
    "Farmer",
    "Fighter",
    "Fisher",
    "Forester",
    "Fortune Teller",
    "Gambler",
    "Guard",
    "Healer",
    "Herbalist",
    "Herder",
    "Historian",
    "Hunter",
    "Investigator",
    "Knight",
    "Labourer",
    "Merchant",
    "Miner",
    "Monk",
    "Monster Hunter",
    "Mystic",
    "Official",
    "Paladin",
    "Performer",
    "Physician",
    "Pirate",
    "Priest",
    "Prospector",
    "Ranger",
    "Ratcatcher",
    "Rebel",
    "Rogue",
    "Sage",
    "Sailor",
    "Scoundrel",
    "Scout",
    "Soldier",
    "Sorcerer",
    "Spy",
    "Squire",
    "Street Urchin",
    "Thief",
    "Tinker",
    "Warlock",
    "Warrior",
    "Witch Hunter",
    "Witch",
    "Wizard",
];

const names = [
    "Absalom",
    "Adeline",
    "Alaric",
    "Alban",
    "Alfgar",
    "Alys",
    "Amalia",
    "Andras",
    "Anthea",
    "Asterius",
    "Astrid",
    "Aurellia",
    "Avisa",
    "Beatrix",
    "Beren",
    "Bertram",
    "Branwen",
    "Bruna",
    "Cael",
    "Camellia",
    "Carrick",
    "Carwyn",
    "Carys",
    "Cassandra",
    "Cassian",
    "Catrin",
    "Cedwyn",
    "Celyn",
    "Ceri",
    "Ceridwen",
    "Cora",
    "Cormac",
    "Corvina",
    "Cuthbert",
    "Darien",
    "Davina",
    "Delphina",
    "Delyth",
    "Duncan",
    "Edwina",
    "Emmanuel",
    "Enoch",
    "Erasmus",
    "Erik",
    "Euphemia",
    "Fergal",
    "Finnian",
    "Flora",
    "Galina",
    "Giles",
    "Gisela",
    "Glyn",
    "Grania",
    "Gwenda",
    "Gwyneth",
    "Hazel",
    "Hyacinthe",
    "Idalia",
    "Idril",
    "Isidora",
    "Isolde",
    "Ivo",
    "Kari",
    "Kayla",
    "Ketil",
    "Killian",
    "Larkin",
    "Lavinia",
    "Lazlo",
    "Lew",
    "Luthien",
    "Maeve",
    "Magdalene",
    "Magnus",
    "Mallory",
    "Marcus",
    "Maxima",
    "Melian",
    "Mielle",
    "Miriel",
    "Moira",
    "Mordecai",
    "Morrigan",
    "Nerys",
    "Nestor",
    "Neve",
    "Niall",
    "Noura",
    "Odine",
    "Osanna",
    "Otto",
    "Ottolia",
    "Padraic",
    "Petra",
    "Philipa",
    "Pietr",
    "Portia",
    "Rafaelina",
    "Renata",
    "Reya",
    "Rhodri",
    "Rhys",
    "Rosaline",
    "Roselle",
    "Rudiger",
    "Sabine",
    "Saskia",
    "Severina",
    "Simeon",
    "Solange",
    "Soren",
    "Talia",
    "Taliesin",
    "Tamsin",
    "Tanith",
    "Taran",
    "Tatius",
    "Theodora",
    "Theodoric",
    "Thiella",
    "Trina",
    "Ulrich",
    "Ulrika",
    "Una",
    "Valda",
    "Valentin",
    "Valerian",
    "Viggo",
    "Waldemar",
    "Willa",
    "Yavanna",
    "Yost",
    "Zahra",
    "Zolli",
    "Zune",
];

const races = [
    "Abyssal",
    "Avian",
    "Beastfolk",
    "Canine",
    "Celestial",
    "Clockwork",
    "Construct",
    "Dragon",
    "Duck",
    "Dwarf",
    "Elf",
    "Fairy",
    "Feline",
    "Gnome",
    "Goblin",
    "Halfling",
    "Human",
    "Insectoid",
    "Kobold",
    "Leshy",
    "Lycanthrope",
    "Merfolk",
    "Myconid",
    "Ogre",
    "Orc",
    "Ratfolk",
    "Reptilian",
    "Shapeshifter",
    "Troll",
    "Undead",
];

const scores = [ 3, 2, 2, 1, 1, 0 ];

const troubles = [
    { text: "Anything for a...", value: "Anything for a" },
    { text: "Can't say no to...", value: "Can't say no to" },
    { text: "Haunted by...", value: "Haunted by" },
    { text: "Have to look after...", value: "Have to look after" },
    { text: "I should know better than to...", value: "I should know better than to" },
    { text: "My darkest secret is...", value: "My darkest secret is" },
    { text: "Never seems to...", value: "Never seems to" },
    { text: "On the run from...", value: "On the run from" },
    { text: "Owe a debt to...", value: "Owe a debt to" },
    { text: "You doubt I can...", value: "You doubt I can" },
];

const data = {
    STORAGE_KEY: STORAGE_KEY,
    adjectives: adjectives,
    approaches: approaches,
    aspects: aspects,
    classes: classes,
    names: names,
    races: races,
    scores: scores,
    troubles: troubles,
};

export { data };
